version: '3'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    # image: wurstmeister/kafka
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      # KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAF_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://zookeeper:9092,OUTSIDE://zookeeper:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://zookeeper:9092,OUTSIDE://zookeeper:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  kafka-manager:
    image: hlebalbau/kafka-manager
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    
networks:
  kafka-network:
    driver: bridge
