version: "2"
networks:
  app-network:
    driver: bridge
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # gRPC
      - "14268:14268"  # HTTP (Collector)
    networks:
      - app-network
  # Collector
  collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /Volumes/BalajiCodebase/springprojects/docker/opencollector/collector-gateway.yaml:/etc/collector-gateway.yaml
    command: [ "--config=/etc/collector-gateway.yaml" ]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      # - tempo
    networks:
      - app-network
  # Tempo
  # tempo:
  #   image: grafana/tempo:latest
  #   ports:
  #     - "3100:3100"  # Default port for Tempo queries
  #     - "9095:9095"  # Default port for OTLP gRPC receiver
  #   volumes:
  #     - /Volumes/BalajiCodebase/springprojects/docker/opencollector/tempo-config.yaml:/etc/tempo.yaml
  #   command: ["-config.file=/etc/tempo.yaml"]    
  # # # Tempo
  # #     - /Volumes/BalajiCodebase/springprojects/docker/opencollector/tempo.yaml:/etc/tempo/tempo.yaml

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - jaeger-all-in-one
      # - tempo

 # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    depends_on:
      - jaeger-all-in-one      
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
