server:
  http_listen_port: 3100
  grpc_listen_port: 9095

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14269
# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:5317
#       http:
#         endpoint: 0.0.0.0:5318

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

compactor:
  compaction:
    block_retention: 48h

query_frontend:
  max_outstanding_per_tenant: 100
